### ISSUE TITLE
Client-app-sample erroneous unsaved changes warning on create individual page

### ISSUE THREAD

**Issue by ghost** [BorderTech/wcomponents-samples#10]
If one opens the "Create individual" view then cancels without making any changes an "unsaved changes" warning is shown. This was raised as [WComponents #1063](https://github.com/BorderTech/wcomponents/issues/1063). 

The cause of this unsaved changes warning is that the table with null option model is not correctly setting the null option's code for the `WDropdown` labelled `Passport country`. When the page is rendered the selected (`null`) option has a `value` of `"1"` but when the `datalist` is loaded with all of the options that `null` option has a value of `""`.

This change of value is the cause of the unsaved changes warning.

**Comment by jonathanaustin** [comment]
LGTM. Thanks for the fix.
